### ISSUE TITLE
Make it tweet

### ISSUE THREAD

**Issue by remram44** [ViDA-NYU/reproducibility-news#4]
Entries could be tweeted as well as published to RSS.

**Comment by VickyRampin** [comment]
Created a twitter for this purpose, [@ReproFeed](https://twitter.com/ReproFeed).

**Comment by remram44** [comment]
Should we use something like [twibble.io](https://twibble.io/)? Do it by hand? Make the build script tweet via tweepy?

**Comment by VickyRampin** [comment]
I wrote a script that does this using tweepy and feedparser, and could try deploying this soon?

**Comment by remram44** [comment]
Is it a good idea or is tweeting by hand acceptable? Doing it manually allows us to customize the message (140 chars & hashtags)

**Comment by VickyRampin** [comment]
I wrote a bot that does this, but I don't really know how to tie it into the build of this repo. Next step!

**Comment by remram44** [comment]
- Either it runs as part on the build (on Travis), and checks what it has already tweeted by reading the Twitter timeline (can't keep state on Travis)
- or we keep it as a bot running somewhere else that reads the RSS and tweets, in which case we can also put its code on GitHub somewhere

**Comment by remram44** [comment]
Will wait on YAML #5
